version: '3'
services:
  app:
    image: golang:1.14
    container_name: reactive_dice
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    - ./assets:/usr/share/accware/assets
    working_dir: /app
    ports:
    - "8080:8080"
    command: [go, run, .]
    environment:
      PORT: "8080"
    env_file:
    - dev.env
