version: '3'
services:
  app:
    image: golang:1.14
    container_name: reactive_dice
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    - ./react/build:/usr/share/reactive-dice/assets
    working_dir: /app
    ports:
    - "8080:80"
    command: [go, run, .]
    env_file:
    - dev.env
