version: '3'
services:
  app:
    image: golang:1.14
    container_name: reactive_dice
    volumes:
    - ./:/app
    - ./cache/mod:/go/pkg/mod
    - ./cache/go-build:/root/.cache/go-build
    - ./react/dist:/usr/share/reactive-dice/assets
    working_dir: /app
    ports:
    - "8080:80"
    command: [go, run, .]
    env_file:
    - dev.env
  webpack:
    image: node:12
    container_name: webpack
    volumes:
    - ./react:/build
    working_dir: /build
    command: [npm, run, watch]
